### ISSUE TITLE
Change Events Field to an array

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/cocina214.com-archive-hugo#14]
> In Forestry, under Pages>Dine>Events it is split up with a “Winter park” photo and text and a “Daytona Beach” photo and text. We sold the Daytona location and want to rework the website without it. On the actual website you don’t see the Daytona info because I don’t have any text written in the Forestry page. See attached photo…. We want to be able to add more pics and text on the Winter Park section for Private Parties and Catering. Maybe up to 6 photos with corresponding text? If we add text and photos it shows up, but if we leave it blank nothing shows up.

see an example in our test set up on forestry https://app.forestry.io/sites/sw-hcr0wuqk4za/#/pages/content-dine-md/

```
events:
  title: Book Your Private Party or Catering
  winter_park_photo: "/uploads/2019/11/19/quesadillas-with-salsa-trio-and-BOAT-for-catering.jpg"
  winter_park_text: 'Please contact Christine, our Private Dining & Events Manager,
    to help plan your private party or catered event. Please allow up to 48hrs for
    a response. Christine can be reached at: Party@Cocina214.com'
  daytona_beach_photo: "/uploads/2019/11/19/Brownies,-Churros-and-Strawberries.jpg"
  daytona_beach_text: ''
```

**Comment by regisphilibert** [comment]
I will need more context @budparr, not sure what is expected of me :)

**Comment by budparr** [comment]
Sorry for not being more clear.

Currently, we have 

```
events:
  title: Book Your Private Party or Catering
  winter_park_photo: "/uploads/2019/11/19/quesadillas-with-salsa-trio-and-BOAT-for-catering.jpg"
  winter_park_text: 'Please contact Christine, our Private Dining & Events Manager,
    to help plan your private party or catered event. Please allow up to 48hrs for
    a response. Christine can be reached at: Party@Cocina214.com'
  daytona_beach_photo: "/uploads/2019/11/19/Brownies,-Churros-and-Strawberries.jpg"
  daytona_beach_text: ''
```

I need it to be something like:

```
events:
 - photo: : "/uploads/2019/11/19/Brownies,-Churros-and-Strawberries.jpg"
   copy: " Some copy here."
 - photo: : "/uploads/2019/11/19/Brownies,-Churros-and-Strawberrie2s@.jpg"
   copy: "New Copy here: It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters"

```

does that make sense?
